[2025-07-15T00:50:16.515+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cross_task_pass_value.multiply_by_100 manual__2025-07-15T00:50:12.764726+00:00 [queued]>
[2025-07-15T00:50:16.519+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cross_task_pass_value.multiply_by_100 manual__2025-07-15T00:50:12.764726+00:00 [queued]>
[2025-07-15T00:50:16.519+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-15T00:50:16.526+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): multiply_by_100> on 2025-07-15 00:50:12.764726+00:00
[2025-07-15T00:50:16.529+0000] {standard_task_runner.py:60} INFO - Started process 2066 to run task
[2025-07-15T00:50:16.532+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cross_task_pass_value', 'multiply_by_100', 'manual__2025-07-15T00:50:12.764726+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/execute_xcom_pass_values.py', '--cfg-path', '/tmp/tmpj9gi7_6k']
[2025-07-15T00:50:16.533+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask multiply_by_100
[2025-07-15T00:50:16.576+0000] {task_command.py:423} INFO - Running <TaskInstance: cross_task_pass_value.multiply_by_100 manual__2025-07-15T00:50:12.764726+00:00 [running]> on host 84e5714b039f
[2025-07-15T00:50:16.618+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='*** ' AIRFLOW_CTX_DAG_ID='cross_task_pass_value' AIRFLOW_CTX_TASK_ID='multiply_by_100' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:50:12.764726+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T00:50:12.764726+00:00'
[2025-07-15T00:50:16.619+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/execute_xcom_pass_values.py", line 15, in multiply_by_100
    value = ti.xcom_pull(task_id='increment_by_1')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-15T00:50:16.625+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cross_task_pass_value, task_id=multiply_by_100, execution_date=20250715T005012, start_date=20250715T005016, end_date=20250715T005016
[2025-07-15T00:50:16.631+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task multiply_by_100 (xcom_pull() got an unexpected keyword argument 'task_id'; 2066)
[2025-07-15T00:50:16.664+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-15T00:50:16.681+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
