[2025-07-11T22:31:19.637+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2025-07-11T22:31:09.704415+00:00 [queued]>
[2025-07-11T22:31:19.642+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2025-07-11T22:31:09.704415+00:00 [queued]>
[2025-07-11T22:31:19.642+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-11T22:31:19.649+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): taskC> on 2025-07-11 22:31:09.704415+00:00
[2025-07-11T22:31:19.652+0000] {standard_task_runner.py:60} INFO - Started process 34210 to run task
[2025-07-11T22:31:19.654+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'executing_multiple_tasks', 'taskC', 'manual__2025-07-11T22:31:09.704415+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/execute_multiple_tasks.py', '--cfg-path', '/tmp/tmp4k_qly_j']
[2025-07-11T22:31:19.656+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask taskC
[2025-07-11T22:31:19.692+0000] {task_command.py:423} INFO - Running <TaskInstance: executing_multiple_tasks.taskC manual__2025-07-11T22:31:09.704415+00:00 [running]> on host 84e5714b039f
[2025-07-11T22:31:19.731+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='*** ' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T22:31:09.704415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-11T22:31:09.704415+00:00'
[2025-07-11T22:31:19.732+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-11T22:31:19.733+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo TASK C has started!\nsleep 10 \nexit 130\necho TASK C has ended!']
[2025-07-11T22:31:19.737+0000] {subprocess.py:86} INFO - Output:
[2025-07-11T22:31:19.738+0000] {subprocess.py:93} INFO - TASK C has started!
[2025-07-11T22:31:29.740+0000] {subprocess.py:97} INFO - Command exited with return code 130
[2025-07-11T22:31:29.747+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2025-07-11T22:31:29.749+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks, task_id=taskC, execution_date=20250711T223109, start_date=20250711T223119, end_date=20250711T223129
[2025-07-11T22:31:29.756+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 34210)
[2025-07-11T22:31:29.764+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-11T22:31:29.775+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
